### PR TITLE
Revert "Migrate multi config tests (#245)"

### PR DESCRIPTION
**Pull request by ymtaye**
This reverts commit 37c3dc5f526c0d2e0a612d7213a8cf82d2125b6c.

# Description of the issue
Tests are failing for this change. Reverting commit while working resolving test failures

# Description of changes
Removed Failing tests (reverted commit)

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
Run tests in private repo gha

### CODE REVIEW

**Review by ZhenyuTan-amz — APPROVED** [review]

**Comment by sethAmazon** [comment]
Should we fix instead of trying to revert?

**Review by zhihonl — COMMENTED** [review]
Can you share the link with the test run that runs all tests so we can make sure this fixes the tests

**Comment by ymtaye** [comment]
> Should we fix instead of trying to revert?

Yes, but I meant to remove this as a immediate resolution since it constantly contaminating integ tests

**Comment by ymtaye** [comment]
> Can you share the link with the test run that runs all tests so we can make sure this fixes the tests
yes, this won't fix the Darwin tests however since this was failing for the run_as_user as cwagent testcase

**Review by sky333999 — APPROVED** [review]

**Pull request merged**
